version: "3.1"
services:
  webserver:
    image: "nginx:alpine"
    container_name: nginx
    working_dir: /application
    volumes:
      - ".:/var/www/html"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"

  php-fpm:
    build: docker/php-fpm
    container_name: php
    working_dir: /application
    volumes:
      - ".:/var/www/html"
      - "./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini"
